---
when:
  event: [push, pull_request, cron, manual]
matrix:
  TARGET:
    - x86_64-apple-darwin
    - aarch64-apple-darwin
    - aarch64-pc-windows-gnullvm
    - x86_64-pc-windows-gnu
    - x86_64-unknown-linux-gnu
    - aarch64-unknown-linux-gnu
    - x86_64-unknown-linux-musl
    - aarch64-unknown-linux-musl
steps:
  build:
    image: code.billie.codes/purplebooth/rust-build-env:latest
    environment:
      CARGO_TERM_COLOR: always
      SCCACHE_S3_ENABLE_VIRTUAL_HOST_STYLE: "true"
      SCCACHE_S3_SERVER_SIDE_ENCRYPTION: "true"
      RUSTC_WRAPPER: sccache
      SCCACHE_BUCKET:
        from_secret: SCCACHE_S3_BUCKET
      SCCACHE_ENDPOINT:
        from_secret: SCCACHE_S3_ENDPOINT
      SCCACHE_REGION:
        from_secret: SCCACHE_S3_REGION
      SCCACHE_S3_USE_SSL: "true"
      SCCACHE_S3_KEY_PREFIX: ${CI_REPO}
      AWS_ACCESS_KEY_ID:
        from_secret: SCCACHE_S3_ACCESS_KEY
      AWS_SECRET_ACCESS_KEY:
        from_secret: SCCACHE_S3_SECRET_KEY
      AWS_EC2_METADATA_DISABLED: "true"
    commands:
      - rustup default stable
      - rustup target add $TARGET
      - cargo zigbuild --release --target $TARGET
