---
when:
  event: [push, pull_request]
matrix:
  TARGET:
    - x86_64-apple-darwin
    - aarch64-apple-darwin
    - aarch64-pc-windows-gnullvm
    - x86_64-pc-windows-gnu
    - x86_64-unknown-linux-gnu
    - aarch64-unknown-linux-gnu
    - x86_64-unknown-linux-musl
    - aarch64-unknown-linux-musl
steps:
  build:
    image: codeberg.org/purplebooth/rust-build-env:latest
    environment:
      CARGO_TERM_COLOR: always
      ZIG_VERSION: 0.15.1  # renovate: datasource=github-releases depName=ziglang/zig
    commands:
      - rustup default stable
      - rustup target add $TARGET
      - cargo zigbuild --release --target $TARGET
