---
when:
  event: [push, pull_request]
matrix:
  RUST: [stable, beta, nightly]
  TARGET:
    - x86_64-apple-darwin
    - aarch64-apple-darwin
    - aarch64-pc-windows-gnullvm
    - x86_64-pc-windows-gnu
    - x86_64-unknown-linux-gnu
    - aarch64-unknown-linux-gnu
    - x86_64-unknown-linux-musl
    - aarch64-unknown-linux-musl
steps:
  build:
    image: rust@sha256:c0601cfa53ef38705af64f72b6b1f2b8afcd8f76de9aa621a8b45b4fa124694c
    environment:
      CARGO_TERM_COLOR: always
      ZIG_VERSION: 0.15.1 # renovate: datasource=github-releases depName=ziglang/zig
    commands:
      - rustup default $RUST
      - rustup target add $TARGET
      - apt update
      - DEBIAN_FRONTEND="noninteractive" apt install --yes build-essential gcc-mingw-w64-x86-64 gcc-mingw-w64-tools nasm
      - curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
      - cargo binstall cargo-zigbuild
      - curl -L https://ziglang.org/download/$${ZIG_VERSION}/zig-x86_64-linux-$${ZIG_VERSION}.tar.xz | tar -xJ -C /opt && ln -s /opt/zig-x86_64-linux-$${ZIG_VERSION}/zig /usr/local/bin/zig && zig version
      - cargo zigbuild --release --target $TARGET
