---
when:
  event: [push, pull_request, cron, manual]
matrix:
  TARGET:
    - x86_64-apple-darwin
    - aarch64-apple-darwin
    - aarch64-pc-windows-gnullvm
    - x86_64-pc-windows-gnu
    - x86_64-unknown-linux-gnu
    - aarch64-unknown-linux-gnu
    - x86_64-unknown-linux-musl
    - aarch64-unknown-linux-musl
steps:
  cache:
    image: quay.io/radicle_garden/plugin-sccache:latest
    volumes:
      - sccache:/sccache_data
    settings:
      save-if: true
      s3-endpoint:
        from_secret: SCCACHE_S3_ENDPOINT
      s3-bucket:
        from_secret: SCCACHE_S3_BUCKET
      s3-key-prefix: $CI_REPO
      s3-access_key:
        from_secret: SCCACHE_S3_ACCESS_KEY
      s3-secret_key:
        from_secret: SCCACHE_S3_SECRET_KEY

  build:
    image: codeberg.org/purplebooth/rust-build-env:latest
    volumes:
      - sccache:/sccache_data
    depends_on: [cache]
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - export PATH="/sccache_data:$PATH"
      - . .sccache
      - rustup default stable
      - rustup target add $TARGET
      - cargo zigbuild --release --target $TARGET
