---
when:
  event: [tag, release]
matrix:
  TARGET:
    - x86_64-apple-darwin
    - aarch64-apple-darwin
    - x86_64-pc-windows-gnu
    - aarch64-pc-windows-gnullvm
    - x86_64-unknown-linux-gnu
    - aarch64-unknown-linux-gnu
    - x86_64-unknown-linux-musl
    - aarch64-unknown-linux-musl
steps:
  build:
    image: codeberg.org/purplebooth/rust-build-env:latest
    environment:
      CARGO_TERM_COLOR: always
      GPG_PRIVATE_KEY:
        from_secret: SIGNING_PRIVATE_KEY
      GPG_PASSWORD:
        from_secret: SIGNING_PRIVATE_PASSWORD
      COSIGN_PRIVATE_KEY:
        from_secret: COSIGN_PRIVATE_KEY
      COSIGN_PASSWORD:
        from_secret: COSIGN_PASSWORD
      FORGEJO_TOKEN:
        from_secret: FORGEJO_TOKEN
    commands:
      - rustup default stable
      - rustup target add $TARGET
      - cargo zigbuild --release --target $TARGET

      # Determine binary name and extension
      - |
        if [ "$TARGET" = *"windows"* ]; then
          BINARY_NAME="whatismyip.exe"
          ARCHIVE_NAME="whatismyip-${TARGET}.exe"
        else
          BINARY_NAME="whatismyip"
          ARCHIVE_NAME="whatismyip-${TARGET}"
        fi

      # Copy binary to standardized name
      - cp target/$TARGET/release/$BINARY_NAME $ARCHIVE_NAME

      # Generate checksums
      - sha256sum $ARCHIVE_NAME > ${ARCHIVE_NAME}.sha256

      # Import GPG key and sign the binary
      - echo "$GPG_PRIVATE_KEY" | gpg --batch --yes --import
      - echo "$GPG_PASSWORD" | gpg --batch --yes --passphrase-fd 0 --pinentry-mode loopback --detach-sign $ARCHIVE_NAME

      # Setup cosign and sign the binary
      - echo "$COSIGN_PRIVATE_KEY" > /tmp/cosign.key
      - chmod 600 /tmp/cosign.key
      - COSIGN_PASSWORD=$COSIGN_PASSWORD cosign sign-blob --yes --key /tmp/cosign.key --output-certificate ${ARCHIVE_NAME}.pem --output-signature ${ARCHIVE_NAME}.sig --bundle ${ARCHIVE_NAME}.bundle $ARCHIVE_NAME
      - rm -f /tmp/cosign.key

      # Upload to forgejo release
      - |
        RELEASE_TAG=$(git describe --tags --exact-match 2>/dev/null || echo $CI_COMMIT_TAG)
        if [ -n "$RELEASE_TAG" ]; then
          # Upload binary
          curl --header "Authorization: token $FORGEJO_TOKEN" \
               --form file=@$ARCHIVE_NAME \
               --form attachment=$(basename $ARCHIVE_NAME) \
               "${CI_REPO_LINK:-https://codeberg.org/${CI_REPO_OWNER}/${CI_REPO_NAME}}/api/v1/repos/${CI_REPO_OWNER}/${CI_REPO_NAME}/releases/$RELEASE_TAG/assets"

          # Upload checksum
          curl --header "Authorization: token $FORGEJO_TOKEN" \
               --form file=@${ARCHIVE_NAME}.sha256 \
               --form attachment=$(basename ${ARCHIVE_NAME}.sha256) \
               "${CI_REPO_LINK:-https://codeberg.org/${CI_REPO_OWNER}/${CI_REPO_NAME}}/api/v1/repos/${CI_REPO_OWNER}/${CI_REPO_NAME}/releases/$RELEASE_TAG/assets"

          # Upload signature
          curl --header "Authorization: token $FORGEJO_TOKEN" \
               --form file=@${ARCHIVE_NAME}.asc \
               --form attachment=$(basename ${ARCHIVE_NAME}.asc) \
               "${CI_REPO_LINK:-https://codeberg.org/${CI_REPO_OWNER}/${CI_REPO_NAME}}/api/v1/repos/${CI_REPO_OWNER}/${CI_REPO_NAME}/releases/$RELEASE_TAG/assets"

          # Upload cosign certificate
          curl --header "Authorization: token $FORGEJO_TOKEN" \
               --form file=@${ARCHIVE_NAME}.pem \
               --form attachment=$(basename ${ARCHIVE_NAME}.pem) \
               "${CI_REPO_LINK:-https://codeberg.org/${CI_REPO_OWNER}/${CI_REPO_NAME}}/api/v1/repos/${CI_REPO_OWNER}/${CI_REPO_NAME}/releases/$RELEASE_TAG/assets"

          # Upload cosign signature
          curl --header "Authorization: token $FORGEJO_TOKEN" \
               --form file=@${ARCHIVE_NAME}.sig \
               --form attachment=$(basename ${ARCHIVE_NAME}.sig) \
               "${CI_REPO_LINK:-https://codeberg.org/${CI_REPO_OWNER}/${CI_REPO_NAME}}/api/v1/repos/${CI_REPO_OWNER}/${CI_REPO_NAME}/releases/$RELEASE_TAG/assets"

          # Upload cosign bundle
          curl --header "Authorization: token $FORGEJO_TOKEN" \
               --form file=@${ARCHIVE_NAME}.bundle \
               --form attachment=$(basename ${ARCHIVE_NAME}.bundle) \
               "${CI_REPO_LINK:-https://codeberg.org/${CI_REPO_OWNER}/${CI_REPO_NAME}}/api/v1/repos/${CI_REPO_OWNER}/${CI_REPO_NAME}/releases/$RELEASE_TAG/assets"
        fi

  publish:
    image: codeberg.org/purplebooth/rust-build-env:latest
    environment:
      CARGO_TERM_COLOR: always
      CARGO_REGISTRY_TOKEN:
        from_secret: CARGO_REGISTRY_TOKEN
    commands:
      - echo cargo publish
