---
when:
  event: [tag, release]
steps:
  publish:
    image: codeberg.org/purplebooth/rust-build-env:latest
    environment:
      CARGO_TERM_COLOR: always
      CARGO_REGISTRY_TOKEN:
        from_secret: CARGO_REGISTRY_TOKEN
    commands: [cargo publish]
