---
when:
  event: [push, pull_request]
  path:
    exclude: [CHANGELOG.md]
steps:
  lint:
    image: rust@sha256:c0601cfa53ef38705af64f72b6b1f2b8afcd8f76de9aa621a8b45b4fa124694c
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - rustup default stable
      - rustup component add rustfmt
      - rustup component add clippy
      - cargo fmt --all -- --check
      - cargo clippy
      - cargo check
