---
depends_on:
  - release-release
when:
  event: [tag]
matrix:
  TARGET:
    - x86_64-apple-darwin
    - aarch64-apple-darwin
    - x86_64-pc-windows-gnu
    - aarch64-pc-windows-gnullvm
    - x86_64-unknown-linux-gnu
    - aarch64-unknown-linux-gnu
    - x86_64-unknown-linux-musl
    - aarch64-unknown-linux-musl
steps:
  build-release-assets:
    image: codeberg.org/purplebooth/rust-build-env:latest
    environment:
      CARGO_TERM_COLOR: always
      GPG_PRIVATE_KEY:
        from_secret: SIGNING_PRIVATE_KEY
      GPG_PASSWORD:
        from_secret: SIGNING_PRIVATE_PASSWORD
      COSIGN_PRIVATE_KEY:
        from_secret: COSIGN_PRIVATE_KEY
      COSIGN_PASSWORD:
        from_secret: COSIGN_PASSWORD
    commands:
      - rustup default stable
      - rustup target add "$$TARGET"
      - cargo zigbuild --release --target "$$TARGET"
      - |
          # Determine binary name and standardized archive name
          case "$$TARGET" in
            *windows*)
              BINARY_NAME="whatismyip.exe"
              ARCHIVE_NAME="whatismyip-$$TARGET.exe"
              ;;
            *)
              BINARY_NAME="whatismyip"
              ARCHIVE_NAME="whatismyip-$$TARGET"
              ;;
          esac
          export BINARY_NAME ARCHIVE_NAME

          # Copy binary to standardized name
          cp "target/$$TARGET/release/$$BINARY_NAME" "$$ARCHIVE_NAME"

          # Generate checksums
          sha256sum "$$ARCHIVE_NAME" > "$$ARCHIVE_NAME.sha256"

          # Import GPG key and create armored signature (.asc)
          echo "$$GPG_PRIVATE_KEY" | gpg --batch --yes --import
          gpg --batch --yes --pinentry-mode loopback --passphrase "$$GPG_PASSWORD" --armor -o "$$ARCHIVE_NAME.asc" --detach-sign "$$ARCHIVE_NAME"

          # Setup cosign and sign the binary
          echo "$$COSIGN_PRIVATE_KEY" > /tmp/cosign.key
          chmod 600 /tmp/cosign.key
          cosign sign-blob --yes --key /tmp/cosign.key --output-certificate "$$ARCHIVE_NAME.pem" --output-signature "$$ARCHIVE_NAME.sig" --bundle "$$ARCHIVE_NAME.bundle" "$$ARCHIVE_NAME"
          rm -f /tmp/cosign.key

  upload-release-assets:
    depends_on: [build-release-assets]
    image: woodpeckerci/plugin-release@sha256:b736e623e8fe27581b4a3999daef2dabd8fc9fe31db6bd3e93bab69add16ff1d
    settings:
      api_key:
        from_secret: CODEBERG_TOKEN
      files:
        - whatismyip-$TARGET*
      file_exists: overwrite
      checksum: sha256
      checksum_file: SHA256SUMS.txt
      checksum_flatten: true