---
variables:
  - &sccache-env
    CARGO_TERM_COLOR: always
    CARGO_INCREMENTAL: '0'
    CMAKE_C_COMPILER_LAUNCHER: sccache
    CMAKE_CXX_COMPILER_LAUNCHER: sccache
    SCCACHE_S3_ENABLE_VIRTUAL_HOST_STYLE: 'false'
    SCCACHE_S3_SERVER_SIDE_ENCRYPTION: 'true'
    RUSTC_WRAPPER: sccache
    SCCACHE_BUCKET: uwu-stirring-cod
    SCCACHE_ENDPOINT: https://fra1.digitaloceanspaces.com
    SCCACHE_REGION: fra1
    SCCACHE_S3_USE_SSL: 'true'
    AWS_ACCESS_KEY_ID:
      from_secret: SCCACHE_S3_ACCESS_KEY
    AWS_SECRET_ACCESS_KEY:
      from_secret: SCCACHE_S3_SECRET_KEY
    AWS_EC2_METADATA_DISABLED: 'true'
when:
  event: [push, pull_request, cron, manual]
steps:
  cargo-test:
    image: code.billie.codes/purplebooth/rust-build-env:latest@sha256:237f98dbf4d776c8723018d4e18c3605f7790fdcfafab039c139084f6f2f4c61
    environment:
      <<: *sccache-env
    commands: [cargo test, sccache --show-stats]
  specdown:
    image: code.billie.codes/purplebooth/rust-build-env:latest@sha256:237f98dbf4d776c8723018d4e18c3605f7790fdcfafab039c139084f6f2f4c61
    environment:
      <<: *sccache-env
    commands:
      - cargo zigbuild --release
      - specdown run --temporary-workspace-dir --add-path "$(pwd)/target/release"
        ./README.md
      - sccache --show-stats
  audit:
    image: woodpeckerci/plugin-trivy@sha256:612038a5ca2d46fd34bb22510ce84f5ce9b605f36304e58faca8ff3edac59eed
    commands: [trivy fs .]
