---
when:
  event: [push, pull_request, cron, manual]
steps:
  cache:
    image: quay.io/radicle_garden/plugin-sccache:latest
    settings:
      save-if: false
      s3-endpoint:
        from_secret: SCCACHE_S3_ENDPOINT
      s3-bucket:
        from_secret: SCCACHE_S3_BUCKET
      s3-key-prefix: $CI_REPO
      s3-access_key:
        from_secret: SCCACHE_S3_ACCESS_KEY
      s3-secret_key:
        from_secret: SCCACHE_S3_SECRET_KEY

  cargo-test:
    image: codeberg.org/purplebooth/rust-build-env:latest
    depends_on: [cache]
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - . ./.sccache
      - cargo test
  specdown:
    image: codeberg.org/purplebooth/rust-build-env:latest
    depends_on: [cache]
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - . ./.sccache
      - cargo zigbuild --release
      - specdown run --temporary-workspace-dir --add-path "$(pwd)/target/release"
        ./README.md
  audit:
    image: woodpeckerci/plugin-trivy@sha256:612038a5ca2d46fd34bb22510ce84f5ce9b605f36304e58faca8ff3edac59eed
    commands: [trivy fs .]
